# Generated by Django 4.2.5 on 2024-07-02 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Campus',
        ),
        migrations.RenameField(
            model_name='campus',
            old_name='city_title',
            new_name='campus_title',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='city',
            new_name='campus',
        ),
    ]
