# Generated by Django 4.2.5 on 2024-07-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_location_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='lat',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='long',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
