# Generated by Django 4.2.5 on 2024-07-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_location_lat_location_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='long',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
