# Generated by Django 4.2.5 on 2024-07-02 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_location_location_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='campus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.campus'),
        ),
    ]
