# Generated by Django 5.0.6 on 2024-07-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_course_alter_location_campus_location_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='course',
        ),
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='degree',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
